// Generated by STFSC export. Do not edit by hand.
use super::scripting::{FuckScript, ScriptContext, ScriptFurrySpecies, ScriptGameMode, ScriptLightType, ScriptPrimitive, ScriptRegistry, ScriptResourceKind, ScriptSandboxProfile, XrHand, XrPoseSpace};

pub fn register_generated_scripts(_registry: &mut ScriptRegistry) {}
